CREATE TABLE public.income_levels (
                                id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                iso2code varchar(3) NOT NULL,
                                code varchar(3) NOT NULL,
                                value varchar(255) NOT NULL,
                                CONSTRAINT income_levels_pkey PRIMARY KEY (id),
                                CONSTRAINT uk_income_value UNIQUE ("value"),
                                CONSTRAINT uk_income_code UNIQUE ("code"),
                                CONSTRAINT uk_income_iso2code UNIQUE ("iso2code")
);