CREATE TABLE public.languages (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              code varchar(3) NOT NULL,
                              name varchar(50) NOT NULL,
                              native_form varchar(50) NOT NULL,
                              CONSTRAINT languages_pkey PRIMARY KEY (id),
                              CONSTRAINT uk_language_name UNIQUE ("name"),
                              CONSTRAINT uk_language_code UNIQUE ("code")

);